### PR TITLE
Removing font-face def and using skin/marketsans

### PR DESCRIPTION
**Pull request by RajaRamu**

### CODE REVIEW

**Comment by senthilp** [comment]
@RajaRamu Did you also do a manual testing on this? Just to make sure the UI looks ok.

**Comment by ianmcburnie** [comment]
LGTM

**Comment by RajaRamu** [comment]
@senthilp - tested locally with browse app. it works fine.

**Comment by senthilp** [comment]
@RajaRamu Please publish a new version. I assume this would be a minor version upgrade.

**Pull request merged**
