### PR TITLE
change renderer to template to make it compatible with marko 4 & 5

### LINKED ISSUE #47: ebay-font has issues with Marko 5
Marko version: `marko@5.0.0-next.45`

It throws the following error:-

```
uncaughtException Unexpected token '<'
node_modules/ebay-font/font/marketsans/template.marko:1
<style nonce=data.nonce>
^

SyntaxError: Unexpected token '<'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:873:16)
    at Function._load (/app/node_modules/brogan-ebay/index.js:37:53)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/ebay-font/font/marketsans/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:873:16)
    at Function._load (/app/node_modules/brogan-ebay/index.js:37:53)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

### PR DESCRIPTION
**Pull request by PrashantAshok**
Fixes #47

### CODE REVIEW

**Review by senthilp — COMMENTED** [review]
Can you please increase the version in `package.json`. Make it a major version change if it will impact Marko V4.

**Comment by PrashantAshok** [comment]
@DylanPiercey - Does this PR look fine to you? I don't think it should impact Marko 4 apps.

**Comment by DylanPiercey** [comment]
@PrashantAshok this should be fine in Marko 3 & 4.

**Review by RajaRamu — APPROVED** [review]
LGTM

**Pull request merged**
